"""HTML report generator using Jinja2."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Template

from evalkit.loader import load_results
from evalkit.models import EvalResult

_REPORT_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>EvalKit Report</title>
<style>
  :root { --pass: #22c55e; --fail: #ef4444; --bg: #0f172a; --card: #1e293b; --text: #e2e8f0; --dim: #94a3b8; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }
  h1 { font-size: 1.5rem; margin-bottom: 1.5rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: var(--card); border-radius: 8px; padding: 1.25rem; }
  .card h2 { font-size: 1rem; color: var(--dim); margin-bottom: 0.75rem; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
  .badge-pass { background: var(--pass); color: #000; }
  .badge-fail { background: var(--fail); color: #fff; }
  .stat { font-size: 2rem; font-weight: 700; }
  table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
  th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #334155; }
  th { color: var(--dim); font-size: 0.75rem; text-transform: uppercase; }
  .bar { height: 6px; border-radius: 3px; background: #334155; }
  .bar-fill { height: 100%; border-radius: 3px; }
  .score-high { background: var(--pass); }
  .score-mid { background: #eab308; }
  .score-low { background: var(--fail); }
  .footer { margin-top: 2rem; color: var(--dim); font-size: 0.75rem; }
</style>
</head>
<body>
<h1>EvalKit Report</h1>

{% for run in runs %}
<div class="grid">
  <div class="card">
    <h2>Suite</h2>
    <div class="stat">{{ run.suite_name }}</div>
    <div style="margin-top: 0.5rem; color: var(--dim);">Model: {{ run.model }}</div>
    <div style="color: var(--dim);">{{ run.timestamp[:19] }}</div>
  </div>
  <div class="card">
    <h2>Status</h2>
    <div class="stat">
      <span class="badge {% if run.passed %}badge-pass{% else %}badge-fail{% endif %}">
        {{ "PASSED" if run.passed else "FAILED" }}
      </span>
    </div>
    <div style="margin-top: 0.5rem;">Pass Rate: {{ "%.1f"|format(run.pass_rate * 100) }}%</div>
  </div>
  <div class="card">
    <h2>Cases</h2>
    <div class="stat">{{ run.passed_cases }}/{{ run.total_cases }}</div>
    <div style="margin-top: 0.5rem;">Mean Score: {{ "%.3f"|format(run.mean_score) }}</div>
  </div>
  <div class="card">
    <h2>Performance</h2>
    <div style="font-size: 1.25rem;">{{ "%.0f"|format(run.total_latency_ms) }}ms total</div>
    <div style="color: var(--dim);">{{ run.total_tokens }} tokens</div>
  </div>
</div>

<div class="card" style="margin-bottom: 2rem;">
  <h2>Per-Case Results</h2>
  <table>
    <tr>
      <th>Case ID</th>
      <th>Status</th>
      <th>Score</th>
      <th>Score Bar</th>
      <th>Metrics</th>
    </tr>
    {% for r in run.results %}
    <tr>
      <td>{{ r.case_id }}</td>
      <td><span class="badge {% if r.passed %}badge-pass{% else %}badge-fail{% endif %}">{{ "PASS" if r.passed else "FAIL" }}</span></td>
      <td>{{ "%.3f"|format(r.weighted_score) }}</td>
      <td>
        <div class="bar" style="width:100px;">
          <div class="bar-fill {% if r.weighted_score >= 0.8 %}score-high{% elif r.weighted_score >= 0.5 %}score-mid{% else %}score-low{% endif %}"
               style="width:{{ (r.weighted_score * 100)|int }}%;"></div>
        </div>
      </td>
      <td style="font-size: 0.8rem; color: var(--dim);">
        {% for mr in r.metric_results %}
          {{ mr.metric_type.value }}: {{ "%.2f"|format(mr.score) }}{% if not loop.last %}, {% endif %}
        {% endfor %}
      </td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endfor %}

<div class="footer">Generated by EvalKit v{{ version }}</div>
</body>
</html>
""")


def generate_report(
    results_dir: str | Path,
    output_path: str | Path = "report.html",
) -> None:
    """Generate an HTML report from all JSONL files in a directory."""
    from evalkit import __version__

    results_dir = Path(results_dir)
    runs: list[EvalResult] = []

    for jsonl_file in sorted(results_dir.glob("*.jsonl")):
        runs.append(load_results(jsonl_file))

    html = _REPORT_TEMPLATE.render(runs=runs, version=__version__)
    Path(output_path).write_text(html)
